/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pkg_id2_dbtools_library_DBTools */

#ifndef _Included_pkg_id2_dbtools_library_DBTools
#define _Included_pkg_id2_dbtools_library_DBTools
#ifdef __cplusplus
extern "C" {
#endif

#define RESULT_OK 1L
#define RESULT_DB_NOT_FOUND 2L
#define RESULT_DB_OPEN_ERROR 3L
#define RESULT_SQL_RUN_ERROR 4L
#define RESULT_TABLE_NOT_FOUND 5L

JNIEXPORT jint JNICALL Java_pkg_id2_dbtools_library_DBTools_nativeGetTableNames
(JNIEnv *, jclass, jstring, jobject);


JNIEXPORT jint JNICALL Java_pkg_id2_dbtools_library_DBTools_nativeGetTableData
(JNIEnv *, jclass, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
