/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pkg_id2_dbtools_library_DBTools */

#ifndef _Included_pkg_id2_dbtools_library_DBTools
#define _Included_pkg_id2_dbtools_library_DBTools
#ifdef __cplusplus
extern "C" {
#endif
#undef pkg_id2_dbtools_library_DBTools_RESULT_DB_NOT_FOUND
#define pkg_id2_dbtools_library_DBTools_RESULT_DB_NOT_FOUND -1024L
#undef pkg_id2_dbtools_library_DBTools_RESULT_DB_OPEN_ERROR
#define pkg_id2_dbtools_library_DBTools_RESULT_DB_OPEN_ERROR -1023L
#undef pkg_id2_dbtools_library_DBTools_RESULT_SQL_RUN_ERROR
#define pkg_id2_dbtools_library_DBTools_RESULT_SQL_RUN_ERROR -1022L
#undef pkg_id2_dbtools_library_DBTools_RESULT_TABLE_NOT_FOUND
#define pkg_id2_dbtools_library_DBTools_RESULT_TABLE_NOT_FOUND -1021L
/*
 * Class:     pkg_id2_dbtools_library_DBTools
 * Method:    nativeGetErrorCode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_pkg_id2_dbtools_library_DBTools_nativeGetErrorCode
  (JNIEnv *, jclass);

/*
 * Class:     pkg_id2_dbtools_library_DBTools
 * Method:    nativeInit
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_pkg_id2_dbtools_library_DBTools_nativeInit
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pkg_id2_dbtools_library_DBTools
 * Method:    nativeRelease
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_pkg_id2_dbtools_library_DBTools_nativeRelease
  (JNIEnv *, jclass);

/*
 * Class:     pkg_id2_dbtools_library_DBTools
 * Method:    nativeGetTableNames
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pkg_id2_dbtools_library_DBTools_nativeGetTableNames
  (JNIEnv *, jclass, jstring);

/*
 * Class:     pkg_id2_dbtools_library_DBTools
 * Method:    nativeGetTableColumnNames
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pkg_id2_dbtools_library_DBTools_nativeGetTableColumnNames
  (JNIEnv *, jclass, jstring, jstring);

/*
 * Class:     pkg_id2_dbtools_library_DBTools
 * Method:    nativeGetTableRowDatas
 * Signature: (Ljava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_pkg_id2_dbtools_library_DBTools_nativeGetTableRowDatas
  (JNIEnv *, jclass, jstring, jstring, jint, jint);

/*
 * Class:     pkg_id2_dbtools_library_DBTools
 * Method:    nativeGetTableQueryDatas
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_pkg_id2_dbtools_library_DBTools_nativeGetTableQueryDatas
  (JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
