/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class pkg_id2_dbtools_library_DBTools */

#ifndef _Included_pkg_id2_dbtools_library_DBTools
#define _Included_pkg_id2_dbtools_library_DBTools
#ifdef __cplusplus
extern "C" {
#endif
#undef pkg_id2_dbtools_library_DBTools_RESULT_OK
#define pkg_id2_dbtools_library_DBTools_RESULT_OK 1L
#undef pkg_id2_dbtools_library_DBTools_RESULT_DB_NOT_FOUND
#define pkg_id2_dbtools_library_DBTools_RESULT_DB_NOT_FOUND 2L
#undef pkg_id2_dbtools_library_DBTools_RESULT_DB_OPEN_ERROR
#define pkg_id2_dbtools_library_DBTools_RESULT_DB_OPEN_ERROR 3L
#undef pkg_id2_dbtools_library_DBTools_RESULT_SQL_RUN_ERROR
#define pkg_id2_dbtools_library_DBTools_RESULT_SQL_RUN_ERROR 4L
#undef pkg_id2_dbtools_library_DBTools_RESULT_TABLE_NOT_FOUND
#define pkg_id2_dbtools_library_DBTools_RESULT_TABLE_NOT_FOUND 5L
/*
 * Class:     pkg_id2_dbtools_library_DBTools
 * Method:    nativeGetTableNames
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_pkg_id2_dbtools_library_DBTools_nativeGetTableNames
  (JNIEnv *, jclass, jstring, jobject);

/*
 * Class:     pkg_id2_dbtools_library_DBTools
 * Method:    nativeGetTableData
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_pkg_id2_dbtools_library_DBTools_nativeGetTableData
  (JNIEnv *, jclass, jstring, jstring, jobject);

#ifdef __cplusplus
}
#endif
#endif
