// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tablenames.proto

#ifndef PROTOBUF_tablenames_2eproto__INCLUDED
#define PROTOBUF_tablenames_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace dbtools_proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_tablenames_2eproto();
void protobuf_AssignDesc_tablenames_2eproto();
void protobuf_ShutdownFile_tablenames_2eproto();

class TableNames;

// ===================================================================

class TableNames : public ::google::protobuf::Message {
 public:
  TableNames();
  virtual ~TableNames();

  TableNames(const TableNames& from);

  inline TableNames& operator=(const TableNames& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const TableNames& default_instance();

  void Swap(TableNames* other);

  // implements Message ----------------------------------------------

  TableNames* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const TableNames& from);
  void MergeFrom(const TableNames& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string name = 1;
  inline int name_size() const;
  inline void clear_name();
  static const int kNameFieldNumber = 1;
  inline const ::std::string& name(int index) const;
  inline ::std::string* mutable_name(int index);
  inline void set_name(int index, const ::std::string& value);
  inline void set_name(int index, const char* value);
  inline void set_name(int index, const char* value, size_t size);
  inline ::std::string* add_name();
  inline void add_name(const ::std::string& value);
  inline void add_name(const char* value);
  inline void add_name(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& name() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_name();

  // @@protoc_insertion_point(class_scope:dbtools_proto.TableNames)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> name_;
  friend void  protobuf_AddDesc_tablenames_2eproto();
  friend void protobuf_AssignDesc_tablenames_2eproto();
  friend void protobuf_ShutdownFile_tablenames_2eproto();

  void InitAsDefaultInstance();
  static TableNames* default_instance_;
};
// ===================================================================


// ===================================================================

// TableNames

// repeated string name = 1;
inline int TableNames::name_size() const {
  return name_.size();
}
inline void TableNames::clear_name() {
  name_.Clear();
}
inline const ::std::string& TableNames::name(int index) const {
  // @@protoc_insertion_point(field_get:dbtools_proto.TableNames.name)
  return name_.Get(index);
}
inline ::std::string* TableNames::mutable_name(int index) {
  // @@protoc_insertion_point(field_mutable:dbtools_proto.TableNames.name)
  return name_.Mutable(index);
}
inline void TableNames::set_name(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:dbtools_proto.TableNames.name)
  name_.Mutable(index)->assign(value);
}
inline void TableNames::set_name(int index, const char* value) {
  name_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:dbtools_proto.TableNames.name)
}
inline void TableNames::set_name(int index, const char* value, size_t size) {
  name_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:dbtools_proto.TableNames.name)
}
inline ::std::string* TableNames::add_name() {
  return name_.Add();
}
inline void TableNames::add_name(const ::std::string& value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:dbtools_proto.TableNames.name)
}
inline void TableNames::add_name(const char* value) {
  name_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:dbtools_proto.TableNames.name)
}
inline void TableNames::add_name(const char* value, size_t size) {
  name_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:dbtools_proto.TableNames.name)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
TableNames::name() const {
  // @@protoc_insertion_point(field_list:dbtools_proto.TableNames.name)
  return name_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
TableNames::mutable_name() {
  // @@protoc_insertion_point(field_mutable_list:dbtools_proto.TableNames.name)
  return &name_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace dbtools_proto

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tablenames_2eproto__INCLUDED
