// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto/tablecolumns.proto

package dbtools_proto;

public final class Tablecolumns {
  private Tablecolumns() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TableColumnOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dbtools_proto.TableColumn)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 index = 1;</code>
     */
    boolean hasIndex();
    /**
     * <code>required int32 index = 1;</code>
     */
    int getIndex();

    /**
     * <code>required string name = 2;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 2;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>required .dbtools_proto.TableColumn.ColumnType type = 3;</code>
     */
    boolean hasType();
    /**
     * <code>required .dbtools_proto.TableColumn.ColumnType type = 3;</code>
     */
    dbtools_proto.Tablecolumns.TableColumn.ColumnType getType();
  }
  /**
   * Protobuf type {@code dbtools_proto.TableColumn}
   */
  public static final class TableColumn extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dbtools_proto.TableColumn)
      TableColumnOrBuilder {
    // Use TableColumn.newBuilder() to construct.
    private TableColumn(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TableColumn(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TableColumn defaultInstance;
    public static TableColumn getDefaultInstance() {
      return defaultInstance;
    }

    public TableColumn getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TableColumn(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              index_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              name_ = bs;
              break;
            }
            case 24: {
              int rawValue = input.readEnum();
              dbtools_proto.Tablecolumns.TableColumn.ColumnType value = dbtools_proto.Tablecolumns.TableColumn.ColumnType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(3, rawValue);
              } else {
                bitField0_ |= 0x00000004;
                type_ = value;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dbtools_proto.Tablecolumns.internal_static_dbtools_proto_TableColumn_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dbtools_proto.Tablecolumns.internal_static_dbtools_proto_TableColumn_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dbtools_proto.Tablecolumns.TableColumn.class, dbtools_proto.Tablecolumns.TableColumn.Builder.class);
    }

    public static com.google.protobuf.Parser<TableColumn> PARSER =
        new com.google.protobuf.AbstractParser<TableColumn>() {
      public TableColumn parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TableColumn(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TableColumn> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code dbtools_proto.TableColumn.ColumnType}
     */
    public enum ColumnType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>INTEGER = 0;</code>
       */
      INTEGER(0, 0),
      /**
       * <code>TEXT = 1;</code>
       */
      TEXT(1, 1),
      /**
       * <code>BLOB = 2;</code>
       */
      BLOB(2, 2),
      /**
       * <code>REAL = 3;</code>
       */
      REAL(3, 3),
      ;

      /**
       * <code>INTEGER = 0;</code>
       */
      public static final int INTEGER_VALUE = 0;
      /**
       * <code>TEXT = 1;</code>
       */
      public static final int TEXT_VALUE = 1;
      /**
       * <code>BLOB = 2;</code>
       */
      public static final int BLOB_VALUE = 2;
      /**
       * <code>REAL = 3;</code>
       */
      public static final int REAL_VALUE = 3;


      public final int getNumber() { return value; }

      public static ColumnType valueOf(int value) {
        switch (value) {
          case 0: return INTEGER;
          case 1: return TEXT;
          case 2: return BLOB;
          case 3: return REAL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ColumnType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<ColumnType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ColumnType>() {
              public ColumnType findValueByNumber(int number) {
                return ColumnType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return dbtools_proto.Tablecolumns.TableColumn.getDescriptor().getEnumTypes().get(0);
      }

      private static final ColumnType[] VALUES = values();

      public static ColumnType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private ColumnType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:dbtools_proto.TableColumn.ColumnType)
    }

    private int bitField0_;
    public static final int INDEX_FIELD_NUMBER = 1;
    private int index_;
    /**
     * <code>required int32 index = 1;</code>
     */
    public boolean hasIndex() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int32 index = 1;</code>
     */
    public int getIndex() {
      return index_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private java.lang.Object name_;
    /**
     * <code>required string name = 2;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private dbtools_proto.Tablecolumns.TableColumn.ColumnType type_;
    /**
     * <code>required .dbtools_proto.TableColumn.ColumnType type = 3;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required .dbtools_proto.TableColumn.ColumnType type = 3;</code>
     */
    public dbtools_proto.Tablecolumns.TableColumn.ColumnType getType() {
      return type_;
    }

    private void initFields() {
      index_ = 0;
      name_ = "";
      type_ = dbtools_proto.Tablecolumns.TableColumn.ColumnType.INTEGER;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasIndex()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt32(1, index_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeEnum(3, type_.getNumber());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, index_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, type_.getNumber());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static dbtools_proto.Tablecolumns.TableColumn parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbtools_proto.Tablecolumns.TableColumn parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbtools_proto.Tablecolumns.TableColumn parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbtools_proto.Tablecolumns.TableColumn parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbtools_proto.Tablecolumns.TableColumn parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static dbtools_proto.Tablecolumns.TableColumn parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static dbtools_proto.Tablecolumns.TableColumn parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static dbtools_proto.Tablecolumns.TableColumn parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static dbtools_proto.Tablecolumns.TableColumn parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static dbtools_proto.Tablecolumns.TableColumn parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(dbtools_proto.Tablecolumns.TableColumn prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dbtools_proto.TableColumn}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dbtools_proto.TableColumn)
        dbtools_proto.Tablecolumns.TableColumnOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dbtools_proto.Tablecolumns.internal_static_dbtools_proto_TableColumn_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dbtools_proto.Tablecolumns.internal_static_dbtools_proto_TableColumn_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dbtools_proto.Tablecolumns.TableColumn.class, dbtools_proto.Tablecolumns.TableColumn.Builder.class);
      }

      // Construct using dbtools_proto.Tablecolumns.TableColumn.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        index_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        type_ = dbtools_proto.Tablecolumns.TableColumn.ColumnType.INTEGER;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dbtools_proto.Tablecolumns.internal_static_dbtools_proto_TableColumn_descriptor;
      }

      public dbtools_proto.Tablecolumns.TableColumn getDefaultInstanceForType() {
        return dbtools_proto.Tablecolumns.TableColumn.getDefaultInstance();
      }

      public dbtools_proto.Tablecolumns.TableColumn build() {
        dbtools_proto.Tablecolumns.TableColumn result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dbtools_proto.Tablecolumns.TableColumn buildPartial() {
        dbtools_proto.Tablecolumns.TableColumn result = new dbtools_proto.Tablecolumns.TableColumn(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.index_ = index_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.type_ = type_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dbtools_proto.Tablecolumns.TableColumn) {
          return mergeFrom((dbtools_proto.Tablecolumns.TableColumn)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dbtools_proto.Tablecolumns.TableColumn other) {
        if (other == dbtools_proto.Tablecolumns.TableColumn.getDefaultInstance()) return this;
        if (other.hasIndex()) {
          setIndex(other.getIndex());
        }
        if (other.hasName()) {
          bitField0_ |= 0x00000002;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasType()) {
          setType(other.getType());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasIndex()) {
          
          return false;
        }
        if (!hasName()) {
          
          return false;
        }
        if (!hasType()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dbtools_proto.Tablecolumns.TableColumn parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dbtools_proto.Tablecolumns.TableColumn) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int index_ ;
      /**
       * <code>required int32 index = 1;</code>
       */
      public boolean hasIndex() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int32 index = 1;</code>
       */
      public int getIndex() {
        return index_;
      }
      /**
       * <code>required int32 index = 1;</code>
       */
      public Builder setIndex(int value) {
        bitField0_ |= 0x00000001;
        index_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 index = 1;</code>
       */
      public Builder clearIndex() {
        bitField0_ = (bitField0_ & ~0x00000001);
        index_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 2;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string name = 2;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            name_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        name_ = value;
        onChanged();
        return this;
      }

      private dbtools_proto.Tablecolumns.TableColumn.ColumnType type_ = dbtools_proto.Tablecolumns.TableColumn.ColumnType.INTEGER;
      /**
       * <code>required .dbtools_proto.TableColumn.ColumnType type = 3;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required .dbtools_proto.TableColumn.ColumnType type = 3;</code>
       */
      public dbtools_proto.Tablecolumns.TableColumn.ColumnType getType() {
        return type_;
      }
      /**
       * <code>required .dbtools_proto.TableColumn.ColumnType type = 3;</code>
       */
      public Builder setType(dbtools_proto.Tablecolumns.TableColumn.ColumnType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000004;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .dbtools_proto.TableColumn.ColumnType type = 3;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000004);
        type_ = dbtools_proto.Tablecolumns.TableColumn.ColumnType.INTEGER;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:dbtools_proto.TableColumn)
    }

    static {
      defaultInstance = new TableColumn(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dbtools_proto.TableColumn)
  }

  public interface TableColumnListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:dbtools_proto.TableColumnList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
     */
    java.util.List<dbtools_proto.Tablecolumns.TableColumn> 
        getColumnList();
    /**
     * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
     */
    dbtools_proto.Tablecolumns.TableColumn getColumn(int index);
    /**
     * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
     */
    int getColumnCount();
    /**
     * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
     */
    java.util.List<? extends dbtools_proto.Tablecolumns.TableColumnOrBuilder> 
        getColumnOrBuilderList();
    /**
     * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
     */
    dbtools_proto.Tablecolumns.TableColumnOrBuilder getColumnOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code dbtools_proto.TableColumnList}
   */
  public static final class TableColumnList extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:dbtools_proto.TableColumnList)
      TableColumnListOrBuilder {
    // Use TableColumnList.newBuilder() to construct.
    private TableColumnList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TableColumnList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TableColumnList defaultInstance;
    public static TableColumnList getDefaultInstance() {
      return defaultInstance;
    }

    public TableColumnList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TableColumnList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                column_ = new java.util.ArrayList<dbtools_proto.Tablecolumns.TableColumn>();
                mutable_bitField0_ |= 0x00000001;
              }
              column_.add(input.readMessage(dbtools_proto.Tablecolumns.TableColumn.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          column_ = java.util.Collections.unmodifiableList(column_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return dbtools_proto.Tablecolumns.internal_static_dbtools_proto_TableColumnList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return dbtools_proto.Tablecolumns.internal_static_dbtools_proto_TableColumnList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              dbtools_proto.Tablecolumns.TableColumnList.class, dbtools_proto.Tablecolumns.TableColumnList.Builder.class);
    }

    public static com.google.protobuf.Parser<TableColumnList> PARSER =
        new com.google.protobuf.AbstractParser<TableColumnList>() {
      public TableColumnList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TableColumnList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TableColumnList> getParserForType() {
      return PARSER;
    }

    public static final int COLUMN_FIELD_NUMBER = 1;
    private java.util.List<dbtools_proto.Tablecolumns.TableColumn> column_;
    /**
     * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
     */
    public java.util.List<dbtools_proto.Tablecolumns.TableColumn> getColumnList() {
      return column_;
    }
    /**
     * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
     */
    public java.util.List<? extends dbtools_proto.Tablecolumns.TableColumnOrBuilder> 
        getColumnOrBuilderList() {
      return column_;
    }
    /**
     * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
     */
    public int getColumnCount() {
      return column_.size();
    }
    /**
     * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
     */
    public dbtools_proto.Tablecolumns.TableColumn getColumn(int index) {
      return column_.get(index);
    }
    /**
     * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
     */
    public dbtools_proto.Tablecolumns.TableColumnOrBuilder getColumnOrBuilder(
        int index) {
      return column_.get(index);
    }

    private void initFields() {
      column_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getColumnCount(); i++) {
        if (!getColumn(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < column_.size(); i++) {
        output.writeMessage(1, column_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < column_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, column_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static dbtools_proto.Tablecolumns.TableColumnList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbtools_proto.Tablecolumns.TableColumnList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbtools_proto.Tablecolumns.TableColumnList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static dbtools_proto.Tablecolumns.TableColumnList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static dbtools_proto.Tablecolumns.TableColumnList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static dbtools_proto.Tablecolumns.TableColumnList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static dbtools_proto.Tablecolumns.TableColumnList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static dbtools_proto.Tablecolumns.TableColumnList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static dbtools_proto.Tablecolumns.TableColumnList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static dbtools_proto.Tablecolumns.TableColumnList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(dbtools_proto.Tablecolumns.TableColumnList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code dbtools_proto.TableColumnList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:dbtools_proto.TableColumnList)
        dbtools_proto.Tablecolumns.TableColumnListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return dbtools_proto.Tablecolumns.internal_static_dbtools_proto_TableColumnList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return dbtools_proto.Tablecolumns.internal_static_dbtools_proto_TableColumnList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                dbtools_proto.Tablecolumns.TableColumnList.class, dbtools_proto.Tablecolumns.TableColumnList.Builder.class);
      }

      // Construct using dbtools_proto.Tablecolumns.TableColumnList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getColumnFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (columnBuilder_ == null) {
          column_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          columnBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return dbtools_proto.Tablecolumns.internal_static_dbtools_proto_TableColumnList_descriptor;
      }

      public dbtools_proto.Tablecolumns.TableColumnList getDefaultInstanceForType() {
        return dbtools_proto.Tablecolumns.TableColumnList.getDefaultInstance();
      }

      public dbtools_proto.Tablecolumns.TableColumnList build() {
        dbtools_proto.Tablecolumns.TableColumnList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public dbtools_proto.Tablecolumns.TableColumnList buildPartial() {
        dbtools_proto.Tablecolumns.TableColumnList result = new dbtools_proto.Tablecolumns.TableColumnList(this);
        int from_bitField0_ = bitField0_;
        if (columnBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            column_ = java.util.Collections.unmodifiableList(column_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.column_ = column_;
        } else {
          result.column_ = columnBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof dbtools_proto.Tablecolumns.TableColumnList) {
          return mergeFrom((dbtools_proto.Tablecolumns.TableColumnList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(dbtools_proto.Tablecolumns.TableColumnList other) {
        if (other == dbtools_proto.Tablecolumns.TableColumnList.getDefaultInstance()) return this;
        if (columnBuilder_ == null) {
          if (!other.column_.isEmpty()) {
            if (column_.isEmpty()) {
              column_ = other.column_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureColumnIsMutable();
              column_.addAll(other.column_);
            }
            onChanged();
          }
        } else {
          if (!other.column_.isEmpty()) {
            if (columnBuilder_.isEmpty()) {
              columnBuilder_.dispose();
              columnBuilder_ = null;
              column_ = other.column_;
              bitField0_ = (bitField0_ & ~0x00000001);
              columnBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getColumnFieldBuilder() : null;
            } else {
              columnBuilder_.addAllMessages(other.column_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        for (int i = 0; i < getColumnCount(); i++) {
          if (!getColumn(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        dbtools_proto.Tablecolumns.TableColumnList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (dbtools_proto.Tablecolumns.TableColumnList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<dbtools_proto.Tablecolumns.TableColumn> column_ =
        java.util.Collections.emptyList();
      private void ensureColumnIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          column_ = new java.util.ArrayList<dbtools_proto.Tablecolumns.TableColumn>(column_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          dbtools_proto.Tablecolumns.TableColumn, dbtools_proto.Tablecolumns.TableColumn.Builder, dbtools_proto.Tablecolumns.TableColumnOrBuilder> columnBuilder_;

      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public java.util.List<dbtools_proto.Tablecolumns.TableColumn> getColumnList() {
        if (columnBuilder_ == null) {
          return java.util.Collections.unmodifiableList(column_);
        } else {
          return columnBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public int getColumnCount() {
        if (columnBuilder_ == null) {
          return column_.size();
        } else {
          return columnBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public dbtools_proto.Tablecolumns.TableColumn getColumn(int index) {
        if (columnBuilder_ == null) {
          return column_.get(index);
        } else {
          return columnBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public Builder setColumn(
          int index, dbtools_proto.Tablecolumns.TableColumn value) {
        if (columnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColumnIsMutable();
          column_.set(index, value);
          onChanged();
        } else {
          columnBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public Builder setColumn(
          int index, dbtools_proto.Tablecolumns.TableColumn.Builder builderForValue) {
        if (columnBuilder_ == null) {
          ensureColumnIsMutable();
          column_.set(index, builderForValue.build());
          onChanged();
        } else {
          columnBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public Builder addColumn(dbtools_proto.Tablecolumns.TableColumn value) {
        if (columnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColumnIsMutable();
          column_.add(value);
          onChanged();
        } else {
          columnBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public Builder addColumn(
          int index, dbtools_proto.Tablecolumns.TableColumn value) {
        if (columnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureColumnIsMutable();
          column_.add(index, value);
          onChanged();
        } else {
          columnBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public Builder addColumn(
          dbtools_proto.Tablecolumns.TableColumn.Builder builderForValue) {
        if (columnBuilder_ == null) {
          ensureColumnIsMutable();
          column_.add(builderForValue.build());
          onChanged();
        } else {
          columnBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public Builder addColumn(
          int index, dbtools_proto.Tablecolumns.TableColumn.Builder builderForValue) {
        if (columnBuilder_ == null) {
          ensureColumnIsMutable();
          column_.add(index, builderForValue.build());
          onChanged();
        } else {
          columnBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public Builder addAllColumn(
          java.lang.Iterable<? extends dbtools_proto.Tablecolumns.TableColumn> values) {
        if (columnBuilder_ == null) {
          ensureColumnIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, column_);
          onChanged();
        } else {
          columnBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public Builder clearColumn() {
        if (columnBuilder_ == null) {
          column_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          columnBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public Builder removeColumn(int index) {
        if (columnBuilder_ == null) {
          ensureColumnIsMutable();
          column_.remove(index);
          onChanged();
        } else {
          columnBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public dbtools_proto.Tablecolumns.TableColumn.Builder getColumnBuilder(
          int index) {
        return getColumnFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public dbtools_proto.Tablecolumns.TableColumnOrBuilder getColumnOrBuilder(
          int index) {
        if (columnBuilder_ == null) {
          return column_.get(index);  } else {
          return columnBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public java.util.List<? extends dbtools_proto.Tablecolumns.TableColumnOrBuilder> 
           getColumnOrBuilderList() {
        if (columnBuilder_ != null) {
          return columnBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(column_);
        }
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public dbtools_proto.Tablecolumns.TableColumn.Builder addColumnBuilder() {
        return getColumnFieldBuilder().addBuilder(
            dbtools_proto.Tablecolumns.TableColumn.getDefaultInstance());
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public dbtools_proto.Tablecolumns.TableColumn.Builder addColumnBuilder(
          int index) {
        return getColumnFieldBuilder().addBuilder(
            index, dbtools_proto.Tablecolumns.TableColumn.getDefaultInstance());
      }
      /**
       * <code>repeated .dbtools_proto.TableColumn column = 1;</code>
       */
      public java.util.List<dbtools_proto.Tablecolumns.TableColumn.Builder> 
           getColumnBuilderList() {
        return getColumnFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          dbtools_proto.Tablecolumns.TableColumn, dbtools_proto.Tablecolumns.TableColumn.Builder, dbtools_proto.Tablecolumns.TableColumnOrBuilder> 
          getColumnFieldBuilder() {
        if (columnBuilder_ == null) {
          columnBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              dbtools_proto.Tablecolumns.TableColumn, dbtools_proto.Tablecolumns.TableColumn.Builder, dbtools_proto.Tablecolumns.TableColumnOrBuilder>(
                  column_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          column_ = null;
        }
        return columnBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:dbtools_proto.TableColumnList)
    }

    static {
      defaultInstance = new TableColumnList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:dbtools_proto.TableColumnList)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dbtools_proto_TableColumn_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dbtools_proto_TableColumn_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_dbtools_proto_TableColumnList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_dbtools_proto_TableColumnList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030proto/tablecolumns.proto\022\rdbtools_prot" +
      "o\"\230\001\n\013TableColumn\022\r\n\005index\030\001 \002(\005\022\014\n\004name" +
      "\030\002 \002(\t\0223\n\004type\030\003 \002(\0162%.dbtools_proto.Tab" +
      "leColumn.ColumnType\"7\n\nColumnType\022\013\n\007INT" +
      "EGER\020\000\022\010\n\004TEXT\020\001\022\010\n\004BLOB\020\002\022\010\n\004REAL\020\003\"=\n\017" +
      "TableColumnList\022*\n\006column\030\001 \003(\0132\032.dbtool" +
      "s_proto.TableColumn"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_dbtools_proto_TableColumn_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_dbtools_proto_TableColumn_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dbtools_proto_TableColumn_descriptor,
        new java.lang.String[] { "Index", "Name", "Type", });
    internal_static_dbtools_proto_TableColumnList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_dbtools_proto_TableColumnList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_dbtools_proto_TableColumnList_descriptor,
        new java.lang.String[] { "Column", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
